### ISSUE TITLE
This script only lists 100 video course in page, can you please update the script to list all courses then dropdown or page for next courses

### ISSUE THREAD

**Issue by AMRUTA-BANDHU-CHAUDHURY** [Anon-Exploiter/infosecinstitute-dl#2]
Hi 

I have tried on ubuntu , it is working fine now. Thanks for this script.
 only it only lists 100 courses, not all .  i can download 100 course, Even after a single course download, download.json file is not updating/to new course fetch DDL to new course. it fails due to below reason saying multiple concurrent connection. 

Also can you please share downloader.py file in this repo. 

```
[&] Please enter any Course Id from the table above (such as 25): 689

[$] Name: Windows Registry Forensics
[$] URL: https://flex.infosecinstitute.com/portal/skills/path/689

[*] Fetching path's description
[*] Fetching videos links
[*] Parsing video links for DDL (might take some time)

Traceback (most recent call last):
  File "infosec.py", line 272, in <module>
    main()
  File "infosec.py", line 256, in main
    for results in executor.map(returnVideoDownloadLink, [host] * len(playlistURL), playlistURL, playlstName):
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

**Comment by Anon-Exploiter** [comment]
Hopefully, fixed in https://github.com/Anon-Exploiter/infosecinstitute-dl/commit/dfa3320bbdba6d7858fdfc64b3c7d60ab8998cc8. 

Can you please confirm if the issue persists? 

The error occurred because a 19.8 GB file was being downloaded and the script panicked after some time. For now, I've added a print statement for just printing URLs like that and don't download them. 

![image](https://user-images.githubusercontent.com/18597330/89119198-b182b300-d4c5-11ea-96a2-a760e0eea896.png)

Thanks for filing this issue @AMRUTA-BANDHU-CHAUDHURY.

**Comment by Anon-Exploiter** [comment]
> only it only lists 100 courses, not all . i can download 100 course, Even after a single course download, download.json file is not updating/to new course fetch DDL to new course. it fails due to below reason saying multiple concurrent connection.

Hi, I've edited README.md, that was supposed to happen in the start but Amazon S3's links expire after 30-40 minutes of generation, so storing the DDL links isn't really going to help us. 

> Also can you please share downloader.py file in this repo.
Remove this from the repository, you can find in old commits. It isn't required anymore. 

I'm also going to remove the instruction which writes into download.json since it is no longer going to be used.

**Comment by Anon-Exploiter** [comment]
> only it only lists 100 courses, not all . i can download 100 course, Even after a single course download, download.json file is not updating/to new course fetch DDL to new course. it fails due to below reason saying multiple concurrent connection.

I've edited README.md, that was supposed to happen in the start but **Amazon S3's links expire after 30-40 minutes** of **generation**, so storing the _DDL_ links isn't really going to help us. 

> Also can you please share downloader.py file in this repo.
Removed it from the repository, you can find in old commits. It isn't required anymore. 

I'm also going to remove the instruction which writes into download.json since it is no longer going to be used.

**Comment by AMRUTA-BANDHU-CHAUDHURY** [comment]
This script only list specific courses, mainly courses which are part of Learning Path. Not all courses, if i pass a specific URL of video course which is not part of any learning path, can i hard code that url in a variable, then script is not working,  can you update the script according to generic one. AS we are updating username and password , like that we will and can update the specific url of the course we want to download. As you have developed the script, you will have a better idea about all the function calls and variable than me even after i am printing each statement on script in debug mode.  still some confusion comes. 

Also i have updated the script based on your commit specified, i tried to download windows forenscis course, it is not working. 
Also some other windows host security and windows server security courses are also not working. 
Can you please cross check and let me know. otherwise if you are coming to discord or telegram, we can chat more about this.

**Comment by Anon-Exploiter** [comment]
@AMRUTA-BANDHU-CHAUDHURY for that you just need to hard code the variable where script is taking input, change that to course URL and others and it'll work. 

More details @ https://github.com/Anon-Exploiter/infosecinstitute-dl/issues/4#issuecomment-669876785

**Comment by Anon-Exploiter** [comment]
The main title's issue has been fixed, closing the issue.
